#!/usr/bin/env python

import os

OKGREEN = '\033[92m'
WARNING = '\033[93m'
RESET_COLOR = '\033[0m'


def install_dotfiles():
    home_dir = os.path.expanduser('~')
    print("installing dotfiles into", home_dir, "...\n")
    for root, _, files in os.walk("/Users/matt/dotfiles"):
        for name in files:
            if not name.endswith('.symlink'):
                continue
            base = '.' + name[:-len('.symlink')]
            dest = os.path.join(home_dir, base)
            if os.path.exists(dest) and not overwrite_existing(dest):
                continue
            source = os.path.join(root, name)
            os.symlink(source, dest)
            print("{}created symlink {} -> {} {}".format(
                OKGREEN, dest, source, RESET_COLOR))
    print("\ndone")


def overwrite_existing(dest):
    if not os.path.islink(dest):
        print("{}{} exists but is not a symlink. Skipping...{}".format(
            WARNING, dest, RESET_COLOR))
        return

    print("A symlink at {} already exists. Overwrite?".format(
        dest), end=' [n]: ')

    if input().lower().startswith('y'):
        os.unlink(dest)
        return True

install_dotfiles()
